version: 2
updates:
  # Configuration for the oc-mirror v1 go mod (weekly security-updates)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable version updates, only allow security updates
    open-pull-requests-limit: 0
    groups:
      oc-mirror-v1-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]

  # Configuration for the oc-mirror v2 go module (monthly version updates)
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      oc-mirror-v2-version-updates:
        applies-to: version-updates
        patterns: [ "*" ]

  # Configuration for the oc-mirror v2 go module (weekly security updates)
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      oc-mirror-v2-security-updates:
        applies-to: security-updates
        patterns: [ "*" ]