version: 2
updates:
  # Configuration for the root Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Disable version updates, only allow security updates
    open-pull-requests-limit: 0
    groups:
      golang-root-security:
        applies-to: security-updates
        patterns: [ "*" ]

  # Configuration for the v2 Go module
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: "daily"
    # Allow all updates (version and security)
    open-pull-requests-limit: 10
    groups:
      golang-v2:
        patterns: [ "*" ]
