---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: operator-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - localhost:5000/cpopen
    source: icr.io/cpopen
  - mirrors:
    - localhost:5000/openshift4
    source: registry.redhat.io/openshift4
