apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-aguidi-dev-catalogs-ibm-multiarch
  namespace: openshift-marketplace
spec:
  image: localhost:5000/home/aguidi/dev/catalogs/ibm-multiarch:6f02ec
  sourceType: grpc
